# ROOT_DIR should be defined in sw/make/Makefile
SW_DIR 	= $(ROOT_DIR)/sw
ITC_DIR = $(SW_DIR)/itc
BIN_DIR = $(SW_DIR)/bin

ITCLIB_DIR = $(BIN_DIR)/libs
UTILSFWK_TRACE_LIBDIR = $(ROOT_DIR)/external/utilsFramework/libs

ITC_CC				:= $(CC)
ITC_AR				:= ar
ITC_CFLAGS 			:= -c -g -Wall -Werror -Wextra -lpthread #-DMUTEX_TRACE_TIME_UNITTEST #-DMUTEX_TRACE_UNITTEST
ITC_ARFLAGS 			:= -rcs
ITC_LDFLAGS 			:= -fPIC
ITC_SOFLAGS 			:= -shared
RMV				:= rm -rf
TARGET_LIBAR			:= libitca.a # Static libary
TARGET_LIBSO			:= libitc.so # Dynamic libary
TARGET_ITCCORD_W_LIBAR		:= itccoord_ar
TARGET_ITCCORD_W_LIBSO		:= itccoord_so
TARGET_ITCGWS_W_LIBAR		:= itcgws_ar
TARGET_ITCGWS_W_LIBSO		:= itcgws_so

all: config_Makefile

config_Makefile:
	@echo "Run sw/make/Makefile.config: Done!!! [OK]"