ROOT_DIR := $(shell git rev-parse --show-toplevel)

SW_DIR 		:= $(ROOT_DIR)/sw
ITC_DIR 	:= $(SW_DIR)/itc
BIN_DIR 	:= $(SW_DIR)/bin
OBJ_DIR 	:= $(BIN_DIR)/obj
LIB_DIR 	:= $(BIN_DIR)/lib
INCLUDE_DIR 	:= $(BIN_DIR)/include
EXEC_DIR 	:= $(BIN_DIR)/exec

# SDKSYSROOT is an env variable which should be exported by doing "source <path-to-SDK>/SDK-***/sysroot/env.sh
# which is automatically done by running atbuild-sdk.sh"
SDK_SYSROOT_DIR		:= $(SDKSYSROOT)
SDK_USR_DIR		:= $(SDK_SYSROOT_DIR)/usr
SDK_LIB_DIR		:= $(SDK_USR_DIR)/lib
SDK_INC_DIR		:= $(SDK_USR_DIR)/include

ITC_CC				:= gcc
ITC_AR				:= ar
ITC_CFLAGS 			:= -c -g -Wall -Werror -Wextra -lpthread -lrt #-DMUTEX_TRACE_TIME_UNITTEST #-DMUTEX_TRACE_UNITTEST
ITC_ARFLAGS 			:= -rcs
ITC_LDFLAGS 			:= -fPIC
ITC_SOFLAGS 			:= -shared
RMV				:= rm -rf
TARGET_LIBAR			:= libitca.a # Static libary
TARGET_LIBSO			:= libitc.so # Dynamic libary
TARGET_ITCCOORD_W_LIBAR		:= itccoord_ar
TARGET_ITCCOORD_W_LIBSO		:= itccoord_so
TARGET_ITCGWS_W_LIBAR		:= itcgws_ar
TARGET_ITCGWS_W_LIBSO		:= itcgws_so